docs: add AVM notice
Azure/terraform-azure-modules pull request #50
Opened 2023-11-09 10:37 UTC by matt-FFFFFF

@lonegunmanb as discussed

/cc @jtracey93 @PmeshramPM

2023-11-10 13:28 UTC, lonegunmanb approved these changes
LGTM! Thanks @matt-FFFFFF but I'd like to get approval from @grayzu .

2023-11-16 01:49 UTC, lonegunmanb commented
I'll merge this pr if @grayzu haven't request change tomorrow.

2023-11-16 13:42 UTC, zioproto requested changes

2023-11-16 13:42 UTC, zioproto commented on README.md
> +This program is merging with [Azure Verified Modules](https://aka.ms/avm) to provide a consistent user experiance across IaC languages on Azure.
typo: experiance -> experience

2023-11-16 13:42 UTC, zioproto commented on README.md
> +New modules will be created under the branding of AVM, so please check the website for more inforamtion.
typo: inforamtion -> information

2023-11-17 01:32 UTC, lonegunmanb commented on README.md
> +New modules will be created under the branding of AVM, so please check the website for more inforamtion.
Good catch, thanks @zioproto!

2023-11-17 01:32 UTC, lonegunmanb requested changes
Hi @matt-FFFFFF would you please check the issues found by @zioproto ? Thanks!

2023-11-20 13:39 UTC, matt-FFFFFF commented
Fixed spelling - ready for re-review

2023-11-21 03:09 UTC, lonegunmanb approved these changes
Thanks @matt-FFFFFF , LGTM!

2023-11-21 03:09 UTC, merged